[package]
name = "t4"
version = "0.2.0"
edition = "2024"
description = "Local embedded high-performance object store."
license = "Apache-2.0"
repository = "https://github.com/XiangpengHao/t4"

[workspace]
members = [".", "fuzz", "verified"]

[features]
default = []
shuttle = ["dep:shuttle"]

[dependencies]
async-task = "4"
crossbeam = "0.8"
crossbeam-channel = "0.5"
libc = "0.2"
log = "0.4"
io-uring = "0.7"
shuttle = { version = "0.8", optional = true }
verified = { package = "t4-verified", version = "0.1.3", path = "verified" }
vstd = "=0.0.0-2026-02-22-0103"

[dev-dependencies]
pollster = "0.4"
tempfile = "3"

[package.metadata.verus]
verify = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(verus_only)'] }
